name: kosmos
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^14.8.1
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/world.png

  fonts:
    - family: SofiaPro
      fonts:
        - asset: assets/fonts/Sofia Pro Regular Az.otf
          weight: 400
        - asset: assets/fonts/Sofia Pro UltraLight Az.otf
          weight: 200
        - asset: assets/fonts/Sofia Pro ExtraLight Az.otf
          weight: 200
        - asset: assets/fonts/Sofia Pro Light Az.otf
          weight: 300
        - asset: assets/fonts/Sofia Pro Medium Az.otf
          weight: 500
        - asset: assets/fonts/Sofia Pro Semi Bold Az.otf
          weight: 600
        - asset: assets/fonts/Sofia Pro Black Az.otf
          weight: 900
        - asset: assets/fonts/Sofia Pro Bold Az.otf
          weight: 700
